version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=munavar
      - POSTGRES_DB=fastapi_db
    ports:
      - "5435:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # FastAPI Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  # Ensure env variables are loaded from .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["uvicorn", "src.__init__:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./src:/app/src

volumes:
  postgres_data:
    driver: local
