"""Update JobApplication to store resume as binary

Revision ID: 890dc6b437b6
Revises: 3f3af6df5d43
Create Date: 2024-10-23 09:13:42.808790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '890dc6b437b6'
down_revision: Union[str, None] = '3f3af6df5d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('JobApplication', sa.Column('resume_file', sa.LargeBinary(), nullable=True))
    op.drop_column('JobApplication', 'cover_letter')
    op.drop_column('JobApplication', 'resume_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('JobApplication', sa.Column('resume_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('JobApplication', sa.Column('cover_letter', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('JobApplication', 'resume_file')
    # ### end Alembic commands ###
