"""Updated User and Message models

Revision ID: a3d40a417bee
Revises: f2819d221964
Create Date: 2024-10-28 13:24:31.588027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'a3d40a417bee'
down_revision: Union[str, None] = 'f2819d221964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('uid', sa.UUID(), nullable=False))
    op.drop_column('message', 'id')
    op.drop_column('message', 'sender_type')
    op.drop_column('message', 'receiver_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('receiver_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('sender_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('message', 'uid')
    # ### end Alembic commands ###
