"""Add otp column to ProviderUser table

Revision ID: d7215b4c1e43
Revises: d92a75fc42f0
Create Date: 2024-10-18 10:56:51.654459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7215b4c1e43'
down_revision: Union[str, None] = 'd92a75fc42f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProviderUser', sa.Column('otp', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('ProviderUser', sa.Column('otp_created_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProviderUser', 'otp_created_at')
    op.drop_column('ProviderUser', 'otp')
    # ### end Alembic commands ###
