"""Rename is_varified to is_verified

Revision ID: d92a75fc42f0
Revises: 0bce9b692d4d
Create Date: 2024-10-16 11:06:26.967048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'd92a75fc42f0'
down_revision: Union[str, None] = '0bce9b692d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('User', 'is_varified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_varified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('User', 'is_verified')
    # ### end Alembic commands ###
