"""Updated User and Message models

Revision ID: f2819d221964
Revises: 890dc6b437b6
Create Date: 2024-10-28 13:04:01.278790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2819d221964'
down_revision: Union[str, None] = '890dc6b437b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Message')
    op.add_column('message', sa.Column('sender_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('message', sa.Column('receiver_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('message_sender_id_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_receiver_id_fkey', 'message', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('message_receiver_id_fkey', 'message', 'ProviderUser', ['receiver_id'], ['uid'])
    op.create_foreign_key('message_sender_id_fkey', 'message', 'User', ['sender_id'], ['uid'])
    op.drop_column('message', 'receiver_type')
    op.drop_column('message', 'sender_type')
    op.create_table('Message',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Message_pkey')
    )
    # ### end Alembic commands ###
